### ISSUE TITLE
Where is Challenge 6?

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-12#1]
It says that the review questions for Phoenix, Madison and Las Vegas cover questions 3 - 6, but there are only three questions (which would only cover 3 -  5). What is challenge 6?

**Comment by wannabeCitizen** [comment]
Hey Chris,

This was a numbering error on my part.

No worries, I fixed it.  It should only be 5 challenges and challenge 6 should be the bonus.

Thanks for catching this,
Mike
