### ISSUE TITLE
Commenters?

### ISSUE THREAD

**Issue by alne4294** [CSCI-4830-002-2014/challenge-week-12#4]
When I run a findOne() on the reddit collection, I get the following:

> db.reddit.findOne()
> {
>     "_id" : ObjectId("54659d9f62bcb1e5f1890392"),
>     "approved_by" : null,
>     "author" : "Hasaan5",
>     "author_flair_css_class" : "other-quest",
>     "author_flair_text" : "Do you even quest, bro? [Scaper since 2004](I still hate suomi)",
>     "banned_by" : null,
>     "body" : "And then people will complain that it isn't exactly like the old one. They will never win over this.",
>     "body_html" : "&lt;div class=\"md\"&gt;&lt;p&gt;And then people will complain that it isn&amp;#39;t exactly like the old one. They will never win over this.&lt;/p&gt;\n&lt;/div&gt;",
>     "created" : 1377723538,
>     "created_utc" : 1377694738,
>     "distinguished" : null,
>     "downs" : 0,
>     "edited" : false,
>     "gilded" : 0,
>     "id" : "cbwxtsz",
>     "likes" : null,
>     "link_id" : "t3_1l8m7k",
>     "link_title" : "Old-school overrides (suggestion)",
>     "name" : "t1_cbwxtsz",
>     "num_reports" : null,
>     "parent_id" : "t1_cbwx93k",
>     "replies" : null,
>     "score_hidden" : true,
>     "subreddit" : "runescape",
>     "subreddit_id" : "t5_2qwxl",
>     "ups" : 1
> }

For challenge 5, how do we know who or how many commenters there are?

**Comment by mynameisfiber** [comment]
That query represents a single commenter (someone who goes by the name of `"author" : "Hasaan5"`).   In addition, the `subreddit` field (`"subreddit" : "runescape"`) says which subreddit this particular comment was posted in.

For challenge 5, you could do many things.  One thing you could do is find all the authors of comments in one subreddit and compare that with the authors in another subreddit (using the Jaccard metric, or any other similar metric).  You could also look at, for example, how many commenters submit multiple comments to a subreddit and use that to compare different subreddits!  The two methods give you different insights, but as long as you understand what the limits of those insights are and what the limitations of them are, they are equally valid.

**Comment by alne4294** [comment]
Oh I see!  Thank you for clarifying.  For some reason, I didn't quite realize that each document represented a comment.
